In [1]:
import cv2
from keras.models import load_model
import numpy as np

model = load_model('./model/keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

with open('./model/labels.txt') as f:
    lines = f.readlines()

labels = []
for line in lines:
    labels.append(line.split(" ")[1])

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    # print(prediction)

    predict_class = labels[np.argmax(np.squeeze(prediction))]
    print(predict_class)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-01-25 21:27:39.068670: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2022-01-25 21:27:39.070740: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


[[3.9462377e-03 3.5482232e-04 1.4195047e-01 8.5374844e-01]]
[[1.2456898e-03 1.4605100e-04 1.8577942e-01 8.1282884e-01]]
[[1.15697556e-04 7.35090289e-05 2.24634826e-01 7.75176048e-01]]
[[2.1214345e-04 8.4354106e-05 3.1503344e-01 6.8467003e-01]]
[[1.8824241e-04 1.0646047e-04 9.9772967e-02 8.9993238e-01]]
[[1.21305915e-04 1.02136481e-04 6.15554601e-02 9.38221157e-01]]
[[2.4607129e-04 1.0272628e-04 1.6509189e-01 8.3455932e-01]]
[[7.5326418e-05 6.5617707e-05 3.7879195e-02 9.6197987e-01]]
[[2.5945648e-05 5.1106752e-05 6.7337908e-02 9.3258506e-01]]
[[3.0320904e-05 1.0166565e-04 9.0074740e-02 9.0979332e-01]]
[[2.3385999e-05 6.9911774e-05 5.6146786e-02 9.4376004e-01]]
[[1.4337689e-04 1.4836303e-04 1.7046328e-01 8.2924497e-01]]
[[1.1547600e-04 1.0572780e-04 2.2719321e-01 7.7258563e-01]]
[[1.7728885e-04 1.5760429e-04 1.9532570e-01 8.0433935e-01]]
[[8.0225189e-05 8.7851033e-05 1.8029681e-01 8.1953520e-01]]
[[1.16729345e-04 1.20890654e-04 2.24536240e-01 7.75226116e-01]]
[[4.0181621e-05 8.7498142e-0

KeyboardInterrupt: 